function SARIMA_trans_sub_temp12 = modelTimeSeries(trans_sub_temp)
%%Time Series Modeling Using the Econometric Modeler
% This code recreates the estimated model produced in the Econometric Modeler app. Use the code below to estimate the same model, or estimate a model with the same parameters on a new set of data.
%
%Input: A numeric matrix with the same number of columns as the data imported into the app (trans_sub_temp)
%
%Output: The model containing estimated parameters (SARIMA_trans_sub_temp12)
%
%Auto-generated by MATLAB Version 9.10 (R2021a) and Econometrics Toolbox Version 5.6 on 28-May-2024 12:15:09
trans_sub_temp1 = trans_sub_temp(:,1);

%% Seasonal ARIMA Model
% Estimate a SARIMA Model of trans_sub_temp1
SARIMA_trans_sub_temp12 = arima('Constant',NaN,'ARLags',1:4,'D',1,'MALags',1:4,'SARLags',[12,24],'Seasonality',12,'SMALags',[12,24],'Distribution','Gaussian');
SARIMA_trans_sub_temp12 = estimate(SARIMA_trans_sub_temp12,trans_sub_temp1,'Display','off');
end